security.basic.enabled: false

logging:
  file: voting-app.log

spring.h2.console:
  enabled: true
  path: /h2

spring.datasource:
  url: "jdbc:h2:file:./votingdb"
  username: votinguser
  password: JDjnrMCr26GDwKEG
  driver-class-name: org.h2.Driver

spring.jpa.generate-ddl: true

ethereum:
  url: http://localhost:8501
  sleepDuration: 100
  attempts: 100
  gas-price: 20000000000
  gas-limit: 10000000
  user-ether-supply: 10
  admin:
    walletAddress: 0xca6fa8ee9c8a374eb41d3f3f1f49ad6167701756
    privateKey: 17646106842132748178533805562811871044955692172000193893877865792463642600494

voters:
  fileName: voters.csv
